spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#server:
#  tomcat:
#    max-swallow-size: 20MB
#
#spring.servlet.multipart:
#  max-file-size: 20MB
#  max-request-size: 20MB

#spring:
#  jpa:
#    database: mysql
#    show-sql: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/user
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver